import Link from "next/link";
import MainLayout from "../components/navbar/layouts/MainLayout";

export default function About() {
	return (
		<MainLayout
			title={"About Page"}
			description={"Generated by create next app"}
		>
			<h1 className="title">
				Go to <Link href="/">Home!</Link>
			</h1>

			<p className="description">
				Get started by editing <code className="code">pages/about.jsx</code>
			</p>
		</MainLayout>
	);
}
