import Link from "next/link";
import MainLayout from "../components/navbar/layouts/MainLayout";

export default function Home() {
	return (
		<MainLayout
			title={"Home Page"}
			description={"Generated by create next app"}
		>
			<h1 className={"title"}>
				Go to <Link href="/about">About!</Link>
			</h1>

			<p className={"description"}>
				Get started by editing <code className={"code"}>pages/index.jsx</code>
			</p>
		</MainLayout>
	);
}
